//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourCircleWebServiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DateSent { get; set; }
        public string Attachements { get; set; }
        public string ClaimedAmount { get; set; }
        public string Description { get; set; }
        public string Client { get; set; }
        public int User_Id { get; set; }
    
        public virtual Users1 Users1 { get; set; }
    }
}
