//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourCircleWebServiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users1()
        {
            this.Claims = new HashSet<Claim>();
            this.Leaves = new HashSet<Leaf>();
            this.Events = new HashSet<Event>();
            this.NoticeBoards = new HashSet<NoticeBoard>();
            this.Projects = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string BasedOffice { get; set; }
        public short Cellphone { get; set; }
        public string PhotoUrl { get; set; }
        public string Role { get; set; }
        public bool isFree { get; set; }
        public System.DateTime DateOfEmployment { get; set; }
        public string Level { get; set; }
        public string ShortDescription { get; set; }
        public string SuperPowers { get; set; }
        public string TechStack { get; set; }
        public string RecoveryKey { get; set; }
        public bool isActive { get; set; }
        public int LunchOrder_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim> Claims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leaf> Leaves { get; set; }
        public virtual LunchOrder LunchOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoticeBoard> NoticeBoards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}
